# Generated by Django 4.2.1 on 2023-05-13 14:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_calllog_contacts_alter_calllog_number_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
