# Generated by Django 4.2.1 on 2023-05-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_smslog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.device'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
