# Generated by Django 4.2.1 on 2023-05-16 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_contacts_device_alter_contacts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Missed', 'Missed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='contacts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='API.contacts'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='Contacts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='API.contacts'),
        ),
    ]
