# Generated by Django 4.2.1 on 2023-05-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_calllog_call_type_alter_calllog_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADBStatus',
            fields=[
                ('connec_status', models.CharField(max_length=255)),
                ('photo_status', models.BooleanField(default=False)),
                ('video_status', models.BooleanField(default=False)),
                ('docs_status', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.device')),
            ],
        ),
        migrations.CreateModel(
            name='DBStatus',
            fields=[
                ('face_data_status', models.BooleanField(default=False)),
                ('call_log_status', models.BooleanField(default=False)),
                ('sms_log_status', models.BooleanField(default=False)),
                ('contacts_status', models.BooleanField(default=False)),
                ('photo_meta_status', models.BooleanField(default=False)),
                ('video_meta_status', models.BooleanField(default=False)),
                ('docs_meta_status', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.device')),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_name', models.CharField(max_length=255)),
                ('docs_path', models.CharField(max_length=1023)),
                ('docs_type', models.CharField(max_length=255)),
                ('docs_size', models.BigIntegerField()),
                ('docs_date_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='adbstatus',
        ),
        migrations.RemoveField(
            model_name='device',
            name='call_log',
        ),
        migrations.RemoveField(
            model_name='device',
            name='contacts_log',
        ),
        migrations.RemoveField(
            model_name='device',
            name='docs_meta',
        ),
        migrations.RemoveField(
            model_name='device',
            name='face_data',
        ),
        migrations.RemoveField(
            model_name='device',
            name='photo_meta',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sms_log',
        ),
        migrations.RemoveField(
            model_name='device',
            name='video_meta',
        ),
        migrations.AddField(
            model_name='device',
            name='android_version',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='battery_level',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_manufacturer',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='vnet_status',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=1023)),
                ('video_type', models.CharField(max_length=255)),
                ('video_size', models.BigIntegerField()),
                ('video_date_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('fps', models.CharField(max_length=255)),
                ('audio_codec', models.CharField(max_length=15)),
                ('audio_channel', models.PositiveSmallIntegerField()),
                ('audio_sample_rate', models.IntegerField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.device')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=255)),
                ('photo_path', models.CharField(max_length=1023)),
                ('photo_type', models.CharField(max_length=255)),
                ('photo_size', models.BigIntegerField()),
                ('pixels', models.CharField(max_length=255)),
                ('color_depth', models.CharField(max_length=255)),
                ('image_comp', models.CharField(max_length=255)),
                ('exif_date_time', models.DateTimeField()),
                ('camera', models.CharField(max_length=255)),
                ('exposure_time', models.DecimalField(decimal_places=9, max_digits=11)),
                ('f_number', models.DecimalField(decimal_places=2, max_digits=4)),
                ('iso_speed', models.IntegerField()),
                ('focal_length', models.DecimalField(decimal_places=5, max_digits=7)),
                ('gps', models.CharField(max_length=255)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.device')),
            ],
        ),
    ]
