# Generated by Django 4.2.1 on 2023-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_adbstatus_dbstatus_docs_remove_device_adbstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_path',
            field=models.CharField(default=None, max_length=1023),
            preserve_default=False,
        ),
    ]
