# Generated by Django 4.2.1 on 2023-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_video_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbstatus',
            name='call_log_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbstatus',
            name='contacts_log_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbstatus',
            name='docs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbstatus',
            name='photo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbstatus',
            name='sms_log_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dbstatus',
            name='video_count',
            field=models.IntegerField(default=0),
        ),
    ]
