# Generated by Django 4.2.1 on 2023-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_dbstatus_call_log_count_dbstatus_contacts_log_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='exposure_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='f_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(max_length=255),
        ),
    ]
