# Generated by Django 4.2.1 on 2023-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_photo_exposure_time_alter_photo_f_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='color_depth',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exif_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exposure_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='f_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gps',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_comp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pixels',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_channel',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_codec',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='audio_sample_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='fps',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
