# Generated by Django 4.2.1 on 2023-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_photo_camera_alter_photo_color_depth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbstatus',
            name='device',
        ),
        migrations.AddField(
            model_name='adbstatus',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
