# Generated by Django 4.2.1 on 2023-05-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_remove_contacts_device_remove_dbstatus_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='device',
        ),
        migrations.RemoveField(
            model_name='video',
            name='device',
        ),
    ]
