# Generated by Django 4.2.1 on 2023-05-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_remove_photo_device_remove_video_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbstatus',
            name='call_log_count',
        ),
        migrations.RemoveField(
            model_name='dbstatus',
            name='contacts_log_count',
        ),
        migrations.RemoveField(
            model_name='dbstatus',
            name='docs_count',
        ),
        migrations.RemoveField(
            model_name='dbstatus',
            name='photo_count',
        ),
        migrations.RemoveField(
            model_name='dbstatus',
            name='sms_log_count',
        ),
        migrations.RemoveField(
            model_name='dbstatus',
            name='video_count',
        ),
    ]
