# Generated by Django 4.2.1 on 2023-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_remove_dbstatus_call_log_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='contacts',
        ),
        migrations.AddField(
            model_name='calllog',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(max_length=255),
        ),
    ]
