# Generated by Django 4.2.1 on 2023-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_remove_calllog_contacts_calllog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='sms_type',
            field=models.CharField(max_length=100),
        ),
    ]
