# Generated by Django 4.2.1 on 2023-05-19 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_alter_photo_exif_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='contacts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='API.contacts'),
        ),
    ]
